sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache:
  directories:
    - node_modules

before_install:
  - npm install -g hexo-cli

install:
  - npm install
  - npm install hexo-renderer-jade hexo-renderer-stylus --save

branches:
  only:
    - source # build master branch only

script:
  - hexo clean
  - hexo generate # generate static files

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: source
  local-dir: public
  target_branch: master
