baseURL = "https://lza852.com/"
languageCode = "en-us"
title = "Justin Lei"
theme = "hugo-ink"

pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsstyle = "vs"

copyright = "© Justin Lei"

[params]
	subtitle = "Study forever"
	avatar = "https://avatars.githubusercontent.com/u/20857777"

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/zianglei"

[markup.goldmark.renderer]
unsafe = true
